### ISSUE TITLE
bp macro

### ISSUE THREAD

**Issue by chrisvwx** [oxinabox/MixedModeDebugger.jl#2]
Despite claims on the readme, it looks like MMD doesn't have quite the same interface as Debugger.jl. Specifically the `@bp` macro doesn't trivially work for me as shown below. 

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using MixedModeDebugger

julia> function f(x)
                  if x < 0
                      @bp
                  else
                      println("All good!")
                  end
              end
ERROR: LoadError: UndefVarError: @bp not defined
in expression starting at REPL[2]:3

julia> 
```

**Comment by oxinabox** [comment]
Yeah,
I forgot about that macro.
It's hard.

You can probably do `using MixedModeDebugger: @bp`
And it will work, but only if it was already switchec to Interpretted Mode, I.e if there was a breakpoint (potentially conditional and not triggered)  further up the callstack.

We rely on having a global list of all breakpoint so as to compile in which functions need to flip over to using the interpretter.

I guess one option might be to scan the code with cassette during compilation looking for whatever `@bp` becomes. And if so determine it needs to run in Interpretted mode.

Another option would be to see if Revise/CodeTracking can identify them for me as they are added. (I don't recall if we have a Revise dependency already).

**Comment by hendri54** [comment]
I have a basic follow-up question: If `@bp` cannot be used to set breakpoints and of course the `bp` command in the `debug` mode is not accessible, how do I set breakpoints?

Thanks for working on this project! Making progress in this direction is important.

**Comment by oxinabox** [comment]
you use the `@breakpoint` macro, and the `breakpoint` function.

It's interesting as someone who sometimes makes debuggers for fun (and not someone who really uses them).
I was unaware that editting the source to add breakpoints, with `@bp` was so popular.
I think if we had known how popular that was, something like Infiltrator.jl would have been available for julia for years and years, and its a much easier problem than being able to insert breakpoints without editting the source.
(though being able to then start stepping forward from the breakpoint probably also is desired).

**Comment by hendri54** [comment]
Thank you - I missed it in the example provided in the Debugger.jl documentation.

**Comment by chrisvwx** [comment]
Thanks for the responses to me and @hendri54

**Comment by fredcallaway** [comment]
Bumping the request for `@bp` support!

**Comment by oxinabox** [comment]
This is not under active develop at this stage.
If you are happy to edit the code to add breakpoints I suggest using Infiltrator.jl instead

**Comment by fredcallaway** [comment]
Ah I didn't realize that Infiltrator actually implements this exactly already. Thanks for the tip!

I will note that there would be substantial value to being able to step forward from the breakpoint (as you mentioned). But I'm sure that this would be very difficult to implement so no worries if you don't have the time!
