### ISSUE TITLE
Difficult to see the colors in the summer benchmark plot legend

### ISSUE THREAD

**Issue by ViralBShah** [oxinabox/MixedModeDebugger.jl#3]
Just a quick usability issue as I was going through the README. I had to click on the image to blow it up in order to be able to see the colors in the legend and map them to the graph.

**Comment by oxinabox** [comment]
You are correct

**Comment by oxinabox** [comment]
This should be better
![image](https://user-images.githubusercontent.com/5127634/71474059-ac43e400-27d1-11ea-9f42-24d9cb43fe70.png)
